layout: sidebar
style: dark

plugins:
  - jekyll-octicons
  - jekyll-github-metadata
  - jemoji

permalink: /:year/:month/:day/:title/

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts"
    values:
      layout: "post"

projects:
  sort_by: stars
  limit: 3
  exclude:
    archived: false
    forks: false
    projects:
      - OSOL.Extremum_API

social_media:
  telegram: wol4aravio
  facebook: panovskiy.v
  instagram: panovskiy.v
  linkedin: panovskiyv
  medium: panovskiy.v
  vk: panovskiy_v
